### ISSUE TITLE
Incrementar a página de eventos e corrigir calendário vazio

### ISSUE THREAD

**Issue by igorsantos07** [PHPRio/phprio.github.io#17]
- [ ] faltou descrevermos eventos antigos e os ocasionais meetups maiores, como o PHP'n Rio
- [ ] também faltou um arquivo melhorado das fotos de eventos do grupo
  > Aproveitando essa parte, podemos colocar algumas fotos mais importantes para ilustrar a página do About.
- [x] o Google Calendar que tá na página, atualmente, está vazio. Como resolver?
  > É ruim precisar lançar os eventos tanto no Meetup.com quanto no Calendar, visto que historicamente o Calendar tende a ser esquecido, abandonado, e fica desatualizado.
  > A sugestão é que adicionemos o iCal do Meetup no Google Calendar do grupo, e assim teremos a integração dos dois e só precisaremos administrar um local. No entanto, não tenho certeza se isso permitirá que as pessoas adicionem o Google Calendar ao delas e vejam os eventos, visto que isso já será exibição de dados de third-party (o usuário vai ver os dados do grupo, que está vendo os dados do Meetup.com).

**Comment by carloshpdoc** [comment]
Sobre o Google Calendar , não sei, mas me parece automatizado, pois sempre que marco um "irei" no meetup, ele me envia um email e já entra no Calendar. Vou ver isso direito e volta aqui. =D

**Comment by cleiver** [comment]
Se sempre que se cria um evento automaticamente o organizador recebe um email com as informações, tem um applet no ITTT.com que pega esse email e automaticamente cria o evento no google calendar...

O problema dessa abordagem é que fica amarrado a uma pessoa ter que organizar/confirmar presença para receber o email...

**Comment by igorsantos07** [comment]
@cleiver E se a gente criar uma conta de email / IFTTT específica pra isso, e colocar esse bot como host em todos os eventos? Acho q seria suficiente e "neutro" (talvez nem precise ser host)

**Comment by cleiver** [comment]
o IFTTT monitora o email pra saber quando tem evento, então se não for problema criar um usuário no meetup para essa conta, acho que funciona.

Não precisa necessariamente ser host, basta receber o email do evento...

**Comment by raphaeldealmeida** [comment]
Podemos usar [API Key signatures](https://www.meetup.com/meetup_api/auth/#keysign) No próprio site da API eles geram essa URL

Gerei esse por exemplo com os eventos do nosso grupo: https://api.meetup.com/PHP-Rio/events?photo-host=public&page=20&sig_id=12508484&sig=2a84e6a41fdf4fc07e094995573e81a351acc408

**Comment by igorsantos07** [comment]
Dois anos depois e o Google desativou calendários embed. Como o calendário já tava vazio, não fazia diferença mesmo, então to removendo.
Até tem o iCal do Meetup.com, mas não consegui exibir isso na página de uma forma simples - não consegui fazer `fetch()` com o iCal pra renderizar com o [ical.js](http://mozilla-comm.github.io/ical.js/), por exemplo.

**Comment by cleiver** [comment]
Não tinha visto essa mensagem de outubro, mas vi hoje quando instalei o app...

Será que rola usar a api do meetup?
https://www.meetup.com/pt-BR/meetup_api/docs/:urlname/events/?uri=%2Fmeetup_api%2Fdocs%2F%3Aurlname%2Fevents%2F#list

**Comment by raphaeldealmeida** [comment]
@cleiver pode mandar um PR com essa alteração?

**Comment by cleiver** [comment]
Posso tentar, provavelmente vai ser via javascript né? 🤔 Meu ponto fraco...

**Comment by giovannism20** [comment]
Fechando a issue dado a falta de movimentação. Caso ainda faça sentido favor reabrir ou abrir um nova referenciando esta.
