### ISSUE TITLE
Empresas parceiras

### ISSUE THREAD

**Issue by vitormattos** [PHPRio/phprio.github.io#30]
Criar sessão no site para as empresas parceiras contendo uma imagem com logo da empresa parceira e link para o site.

Os dados das empresas parceiras devem vir de um arquivo json de metadados a ser processado na hora que é feito o build do site para geração do html para prod.

**Comment by vitormattos** [comment]
Pode ser a princípio estas 3:

https://www.funcionalcorp.com.br/
https://www.meupatrocinio.com/
https://www.rj.senac.br/

Depois vamos aumentando a lista

**Comment by igorsantos07** [comment]
Fiz um layout pra até 3 logos por linha. O conteúdo é submetido via metadados do próprio Sculpin - ou seja, YAML em `app/config/sculpin_site.yml` :)

![image](https://user-images.githubusercontent.com/532299/67913284-43dadc80-fb6b-11e9-9af8-c7b2b5e4e06b.png)
