### ISSUE TITLE
Inclusão de "Don't ask to ask, just ask" no COC

### ISSUE THREAD

**Issue by vitormattos** [PHPRio/phprio.github.io#38]
Incluir informações de "Don't ask to ask, just ask" e link para https://dontasktoask.com no código de conduta http://php.rio/coc/

Sugestão: Talvez seja uma boa inserir no tópico "seja questionador".

**Comment by giovannism20** [comment]
Fechando essa issue pois o código de conduta é mantido em [outro repositório agora](https://github.com/PHPRio/code-of-conduct) e foi adicionado por lá de qualquer forma.
Link para o commit em PT-BR: https://github.com/PHPRio/code-of-conduct/commit/0e5f053358ec991f993f8a6b5f191527092ddebc
Link para o commit em EN: https://github.com/PHPRio/code-of-conduct/commit/ab27c95c5fc544a0b7c71b4f6bec06e7d6135c7b
