### ISSUE TITLE
Forçar HTTPS

### ISSUE THREAD

**Issue by lhsazevedo** [PHPRio/phprio.github.io#39]
Por enquanto o site ainda pode ser acessado via HTTP.
O GitHub pages oferece a funcionalidade de [forçar HTTPS](https://docs.github.com/pt/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https) que irá redirecionar os usuários para a versão segura do site.

**Comment by lhsazevedo** [comment]
Tentei ativar agora mas a opção está bloqueada. Segundo [esse artigo](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site), pode levar até 24 horas para a opção esteja disponível.

**Comment by lhsazevedo** [comment]
A opção de forçar HTTPS não está disponível pois estamos usando o serviço e certificados da Cloudflare ([fonte](https://github.community/t/github-pages-can-t-enforce-https-for-custom-domain/121369/2)). Essa opção deve ser ativada no painel deles: [Always Use HTTPS - Cloudflare SSL/TLS docs](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/).

@vitormattos @igorsantos07

**Comment by lhsazevedo** [comment]
Aproveitando, como é feita a gestão da Cloudflare e do próprio domínio .rio? Custos de renovação, registros DNS, essas coisas...

**Comment by igorsantos07** [comment]
Quem administra os domínios sou eu, @lhsazevedo :)

Habilitei a opção que você indicou no Cloudflare do php.rio e do phprio.org. Não consegui habilitar a opção aqui no GH Pages, provavelmente deve depender das tais 24h que você comentou. Então a issue fica aberta pra revisarmos em breve.

Sobre os custos e registros, a cada 3 anos a gente costuma fazer uma campanha de arrecadação sobre esses custos, e eu fico responsável pelos registros (como já deve ter imaginado). Isso começou pois eu me candidatei a interagir com o pessoal do `.rio` pra conseguir nosso domínio, há 6 anos (e sim, esse ano provavelmente vamos fazer novamente).
Atualmente o .rio tá num registrar do leste europeu (o mais em conta) e o .org.... Acho que é no GoDaddy, onde o administrador antigo criou.

Talvez o .org seja desativado em algum momento, mas ainda não tomamos a decisão?
Aproveitando o assunto... Anexo aqui estatísticas do CF sobre os dois domínios. O phprio.org retorna um `301 Moved Permanently` para o php.rio há 6 anos, e mesmo assim ainda parece ter acessos frequentes, mas... Olhando mais a fundo, nos últimos 30 dias houve 31 acessos nacionais, e o restante foi dos EUA/Rússia/China - bots? É curioso que um domínio de redirect tenha 3x mais requests do que visitantes únicos, também.

![image](https://user-images.githubusercontent.com/532299/175831184-975eb4c9-e092-4456-a6f4-41902e9d054c.png)
![image](https://user-images.githubusercontent.com/532299/175831338-95e00a6b-1b26-433b-abd1-2a5104ca5dfb.png)

![image](https://user-images.githubusercontent.com/532299/175831186-c3a18220-67c7-4500-9504-b9b2d91556be.png)
![image](https://user-images.githubusercontent.com/532299/175831285-ef1b8c82-0ac2-4511-8805-feb30f3a00b5.png)



Valeu!

**Comment by lhsazevedo** [comment]
Testei aqui e já está funcionando :+1: 
```
$ curl -i http://php.rio
HTTP/1.1 301 Moved Permanently
(...)
Location: https://php.rio/
(...)
```

> Não consegui habilitar a opção aqui no GH Pages, provavelmente deve depender das tais 24h que você comentou.

O prazo de 24h seria apenas apontássemos os registros DNS diretamente para os IPs do GitHub, removendo o Cloudflare. Nesse caso eles pediriam 24h para ativar a opção "Enforce HTTPS". Mas como estamos fazendo isso diretamente no CF, não será mais necessário ativar essa opção...

> bots?

Imagino que  sejam bots mesmo, esse domínio deve aparecer em várias listas por causa das contas de email. Um dia a gente ultrapassa eles rs

> Talvez o .org seja desativado em algum momento, mas ainda não tomamos a decisão?

Parece que não foi decidido por enquanto. Vi que o assunto do domínio .org e do servidor de emails acabou ressurgindo no grupo agora que a edição legada do GSuite está para expirar. E tem a situação do meetup.com também...

Parece que alcançamos o objetivo dessa issue aqui. Me avisa quando forem se reunir pra discutir as outras pendências que eu tento contribuir de alguma maneira.  Muito obrigado :)
