### ISSUE TITLE
Erro 404 - pagina código de conduta 

### ISSUE THREAD

**Issue by Cristianpl4y** [PHPRio/phprio.github.io#56]
existe um código de conduta? 

![image](https://user-images.githubusercontent.com/55006128/206255510-9561b6e4-00ef-441b-acab-860be241c291.png)

**Comment by Cristianpl4y** [comment]
Se não existe podemos criar, o que vocês acham? 👀

**Comment by vitormattos** [comment]
Existe um sim mas até hoje não colocamos no site.

É este:
https://github.com/PHPRio/code-of-conduct

Talvez possamos colocar o arquivo .md do código de conduta no site e após fazer o deploy (automatizado após merge do PR na branch main), arquivar o repo do código de conduta. Que tal?

**Comment by Cristianpl4y** [comment]
> Existe um sim mas até hoje não colocamos no site.
> 
> É este: https://github.com/PHPRio/code-of-conduct
> 
> Talvez possamos colocar o arquivo .md do código de conduta no site e após fazer o deploy (automatizado após merge do PR na branch main), arquivar o repo do código de conduta. Que tal?

Ótima ideia! Colocar o código de conduta no site parece um bom caminho. Arquivar o repositório depois faz sentido também. Vamos seguir com isso 😏

**Comment by vitormattos** [comment]
Se quiser pegar esta para fazer, dá o assign da issue para você e mete bronca no PR.

**Comment by Cristianpl4y** [comment]
@vitormattos realizei a atualização do arquivo .md referente ao código de conduta. Espero que essa contribuição seja útil para o projeto. Não consegui assumir a issue diretamente, mas já abri o PR.

Fico à disposição para quaisquer ajustes ou comentários!
